### ISSUE TITLE
Can't find `bash` at `/usr/bin/bash`

### ISSUE THREAD

**Issue by Aariq** [eco4cast/gefs4cast#7]
I get an error running `gefs_cog()`:

``` r
library(gefs4cast)
gefs_cog()
#> Error in c("process_initialize(self, private, command, args, stdin, stdout, ", : ! Native call to `processx_exec` failed
#> Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
#> ! cannot start processx process '/usr/bin/bash' (system error 2, No such file or directory) @unix/processx.c:613 (processx_exec)
```

<sup>Created on 2022-12-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
Similar to #5, it looks like there are some assumptions made in the package about where bash is. For me (macOs 13.1) it's at `/bin/bash`, not `/usr/bin/bash`.

If I run `debugonce(gefs4cast:::gdal_download)` and replace `p <- processx::run("/usr/bin/bash", shell)` with `p <- processx::run("bash", shell)` I think it works fine though.

**Comment by cboettig** [comment]
yeah, we definitely need to clean up our PATH issues.  (I'm sure there was a reason to use absolute paths but now no idea what that was... I think we were running with `littler` which doesn't load environmental variables including PATH).  I'll drop the absolute paths and see where we get.  

@rqthomas I think we should drop the `littler` use in the cron jobs, and use `score4cast::ignore_sigpipes()` in scripts that error on the sigpipe issue....

**Comment by cboettig** [comment]
ok, pushed a version with no hard paths, lemme know if that doesn't fix this (should resolve #5 as well)

**Comment by Aariq** [comment]
`gefs_cog()` runs now without error, but it doesn't seem to download anything.
```

**Comment by cboettig** [comment]
what gdal version do you have?  (it should complain if it doesn't find GDAL >= 3.4 )...
